# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 11:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=45)),
                ('addresscol', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='JdGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('comment_num', models.IntegerField(blank=True, null=True)),
                ('goods_id', models.CharField(max_length=25)),
                ('link', models.CharField(max_length=50)),
                ('commentversion', models.CharField(blank=True, db_column='commentVersion', max_length=25, null=True)),
                ('score1count', models.CharField(blank=True, max_length=25, null=True)),
                ('score2count', models.CharField(blank=True, max_length=25, null=True)),
                ('score3count', models.CharField(blank=True, max_length=25, null=True)),
                ('score4count', models.CharField(blank=True, max_length=25, null=True)),
                ('score5count', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('jd_goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.JdGoods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('total_price', models.CharField(max_length=25)),
                ('jd_goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.JdGoods')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.IntegerField()),
                ('active', models.IntegerField()),
                ('create_time', models.DateField(default=django.utils.timezone.now)),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Address')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.User'),
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.User'),
        ),
        migrations.AddField(
            model_name='jdgoods',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.Shop'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.City'),
        ),
    ]
