# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JdGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('comment_num', models.IntegerField(blank=True, null=True)),
                ('goods_id', models.CharField(max_length=25)),
                ('link', models.CharField(max_length=50)),
                ('commentversion', models.CharField(blank=True, db_column='commentVersion', max_length=25, null=True)),
                ('score1count', models.CharField(blank=True, max_length=25, null=True)),
                ('score2count', models.CharField(blank=True, max_length=25, null=True)),
                ('score3count', models.CharField(blank=True, max_length=25, null=True)),
                ('score4count', models.CharField(blank=True, max_length=25, null=True)),
                ('score5count', models.CharField(blank=True, max_length=25, null=True)),
                ('price', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'jd_goods',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'label',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('total_price', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=25)),
                ('active', models.IntegerField()),
                ('create_time', models.DateField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('idaddress', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=45)),
                ('addresscol', models.CharField(blank=True, max_length=45, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.City')),
            ],
        ),
    ]
