# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JDBookItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=25)),
                ('keywords', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=25)),
                ('channel', models.CharField(max_length=25)),
                ('tag', models.CharField(max_length=25)),
                ('sub_tag', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='jd_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.JDBookItem'),
        ),
    ]
