# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170511_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='jdbookitem',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
